In [16]:
from qiskit import QuantumCircuit
import qiskit.quantum_info as qi


# to define a two qubit circuit...
circ = QuantumCircuit(2,1)
circ.x(0)
circ.draw()


┌───┐
q_0: ┤ X ├
     └───┘
q_1: ─────
          
c: 1/═════

In [17]:
op = qi.Operator(circ)
print(op)

Operator([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
          [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
          [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))


In [19]:
import qiskit.quantum_info as qi

# to define an 18 qubit circuit...

circ = QuantumCircuit(20,1)
circ.x(0)
circ.draw()


┌───┐
 q_0: ┤ X ├
      └───┘
 q_1: ─────
           
 q_2: ─────
           
 q_3: ─────
           
 q_4: ─────
           
 q_5: ─────
           
 q_6: ─────
           
 q_7: ─────
           
 q_8: ─────
           
 q_9: ─────
           
q_10: ─────
           
q_11: ─────
           
q_12: ─────
           
q_13: ─────
           
q_14: ─────
           
q_15: ─────
           
q_16: ─────
           
q_17: ─────
           
q_18: ─────
           
q_19: ─────
           
 c: 1/═════

In [20]:
op = qi.Operator(circ)

print(op)

MemoryError: Unable to allocate 8.00 TiB for an array with shape (1048576, 1048576) and data type float64

In [11]:
# Uh oh. Why did that happen?

((((2**20)*(2**20))*64)/8)*0.9


7916483719987.2

In [12]:
# can construct multi-qubit gates using numpy as well
import numpy as np

X = np.array([[0,1],[1,0]])
I = np.array([[1,0],[0,1]])

np.kron(I,X)

array([[0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0]])

In [13]:
np.kron(X,X)

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [14]:
# could check the two-qubit states...

up = np.array([1,0])
down = np.array([0,1])

print(np.kron(up,up))
print(np.kron(up,down))
print(np.kron(down,up))
print(np.kron(down,down))

[1 0 0 0]
[0 1 0 0]
[0 0 1 0]
[0 0 0 1]


In [15]:
# When defining circuits, we can extract the net unitary formed by the gates applied

circ = QuantumCircuit(2,1)
circ.x(0)


from qiskit import Aer, execute # Import Aer and execute

backend_sim = Aer.get_backend('unitary_simulator') #create backend object

#job execution and getting the result as an object
job = execute(circ, backend_sim)
result = job.result()

print(result.get_unitary(circ, decimals=3))

Operator([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
          [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
          [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
          [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]],
         input_dims=(2, 2), output_dims=(2, 2))
